services:
  docusaurus:
    image: docker.io/node:22.21-alpine3.23
    container_name: docusaurus
    working_dir: /app
    command: ["sh", "-c", "npm run start"]
    profiles:
      - dev
    networks:
      - radix-public-site
    ports:
      - "8001:8000"
    volumes:
      - type: bind
        source: .
        target: /app

  proxy:
    image: docker.io/nginxinc/nginx-unprivileged:1.29.3-alpine3.22
    container_name: proxy
    profiles:
      - dev
    networks:
      - radix-public-site
    ports:
      - "8081:8080"
    depends_on:
      - docusaurus
    volumes:
      - type: bind
        read_only: true
        target: /etc/nginx/conf.d/default.conf
        source: ./proxy/server.dev.conf
      - type: bind
        read_only: true
        target: /etc/nginx/conf.d/securityheaders
        source: ./proxy/securityheaders

  production:
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - prod
    ports:
      - "8081:8080"

networks:
  radix-public-site:
    name: radix-public-site
