site_name: Omnia Radix
copyright: Equinor ASA @ 2025
site_description: >-
  Radix is a platform for building and running applications in the cloud,
  designed to simplify the development and deployment process.
docs_dir: docs
extra_css:
  - global.css
theme:
    name: material
    features:
        - content.code.copy
plugins:
    - search
    - docusaurus
    - techdocs-core
markdown_extensions:
  - admonition
  - md_in_html
  - def_list
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
nav:
  - Getting started:
      - What is Radix: start/index.md
      - Radix concepts: start/radix-concepts/index.md
      - Getting access: start/getting-access/index.md
      - Requirements: start/requirements/index.md
      - Configuring your application: start/config-your-app/index.md
      - Registering your application: start/registering-app/index.md
      - Workflows: start/workflows/index.md
      - Radix clusters: start/radix-clusters/index.md
      - Onboarding: start/onboarding/index.md
      - Examples: start/examples/index.md
      - When not to use Radix: start/not-radix/index.md
  - Docs:
      - Docs: docs/index.md
      - What's new: docs/topic-releases/index.md
      - Docker & containers: docs/topic-docker/index.md
      - Runtime environment: docs/topic-runtime-env/index.md
      - Logs: docs/topic-logs/index.md
      - Security: docs/topic-security/index.md
      - Vulnerability scanning: docs/topic-vulnerabilities/index.md
      - Monitoring concepts: docs/topic-monitoring/index.md
      - Domain names: docs/topic-domain-names/index.md
      - Private Link / Endpoint: docs/topic-private-link/index.md
      - Radix cost: docs/topic-cost/index.md
      - Rolling updates: docs/topic-rollingupdate/index.md
      - Service, support, uptime and availability: docs/topic-uptime/index.md
      - Radix CLI: docs/topic-radix-cli/index.md
      - Code editor integrations: docs/topic-code-editor-integration/index.md
      - Integrate Dynatrace in a Radix app: docs/topic-dynatrace-int/index.md
      - Redis Cache: docs/topic-redis/index.md
  - Radix Config: radix-config/index.md
  - Guides:
      - Radix guides: guides/index.md
      - Docker:
          - What is a container: guides/docker/index.md
          - Users in containers: guides/docker-useradd/index.md
      - CI/CD Pipeline:
          - Build and Deploy: guides/build-and-deploy/index.md
          - Deploy Using External CI/CD Tools: guides/deploy-only/index.md
          - Deployment Promotion: guides/deployment-promotion/index.md
          - Apply Config: guides/apply-config/index.md
          - Sub-pipeline: guides/sub-pipeline/index.md
          - Pipeline Badges: guides/pipeline-badge/index.md
      - Build Secrets: guides/build-secrets/index.md
      - Environment Variables: guides/environment-variables/index.md
      - Authentication:
          - OAuth 2.0 Authentication: guides/authentication/index.md
          - Azure Workload Identity: guides/workload-identity/index.md
      - Azure Key Vault: guides/azure-key-vaults/index.md
      - External DNS Alias:
          - DNS Alias and certificate: guides/external-alias/index.md
          - Manual add Certificate: guides/external-alias-certificate/index.md
      - Jobs:
          - Overview: guides/jobs/index.md
          - Configuring jobs: guides/jobs/configure-jobs.md
          - Job manager and job API: guides/jobs/job-manager-and-job-api.md
          - Notifications: guides/jobs/notifications.md
          - Environment variables: guides/jobs/environment-variables.md
          - Managing Jobs in Web Console: guides/jobs/jobs-in-web-console.md
          - OpenAPI/Swagger spec: guides/jobs/openapi-swagger.md
      - Volume Mounts:
          - Azure Storage Account: guides/volume-mounts/index.md
          - Limitations / Known Issues: guides/volume-mounts/limitations.md
      - Horizontal Scaling:
          - Overview: guides/horizontal-scaling/index.md
          - Azure Service Bus:
              - Overview: >-
                  guides/horizontal-scaling/keda-azure-service-bus-trigger-overview.md
              - Authentication: >-
                  guides/horizontal-scaling/keda-azure-service-bus-trigger-authentication.md
          - Azure Event Hub:
              - Overview: >-
                  guides/horizontal-scaling/keda-azure-event-hub-trigger-overview.md
              - Authentication: >-
                  guides/horizontal-scaling/keda-azure-event-hub-trigger-authentication.md
              - Events: >-
                  guides/horizontal-scaling/keda-azure-event-hub-trigger-events.md
      - Private Links: guides/private-link/index.md
      - Enable and disable components: guides/enable-and-disable-components/index.md
      - Component scale/stop/restart: guides/component-start-stop-restart/index.md
      - Resource request and limit: guides/resource-request/index.md
      - Egress: guides/egress-config/index.md
      - Monitoring:
          - Metrics: guides/monitoring/index.md
          - Alerting: guides/alerting/index.md
      - GitHub:
          - Git submodules: guides/git-submodules/index.md
          - Monorepo: guides/monorepo/index.md
  - Features: features/index.md
  - Community: community/index.md
  - Web Console: https://console.radix.equinor.com/
